# fly.toml app configuration file generated for server-zukhra-oskar-alex on 2024-02-07T14:57:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-zukhra-oskar-alex'
primary_region = 'lhr'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/nodejs']

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
